# Generated by Django 4.2.7 on 2025-02-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_name', models.CharField(max_length=200)),
                ('rule_id', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('diff_url', models.URLField(blank=True, null=True)),
                ('diff_data', models.TextField(blank=True, null=True)),
                ('diff_image', models.URLField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='account.users')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='account.users')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='account.users')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_by', to='account.users')),
            ],
            options={
                'verbose_name_plural': 'KnownDiffs',
                'db_table': 'known_diff',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['diff_name'], name='idx_diff_name')],
            },
        ),
    ]
