# Generated by Django 4.2.7 on 2025-02-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diff_patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowndiff',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
