# Generated by Django 4.2.7 on 2025-02-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diff_patterns', '0002_knowndiff_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowndiff',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='knowndiff',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowndiff',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
