# Generated by Django 4.2.7 on 2025-02-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('diff_patterns', '0003_remove_knowndiff_is_approved_knowndiff_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowndiff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='account.users'),
        ),
    ]
